version: '3.3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: evaluatedb
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:

